Riddle.create(question: "How is the moon like a dollar?", answer: "They both have four quarters.", keyword: "quarters")
Riddle.create(question: "How could a cowboy ride into town on Friday, stay two days, and ride out on Friday?", answer: "His horse's name is called Friday.", keyword: "horse")
Riddle.create(question: "If you have me, you want to share me. If you share me, you haven't got me. What am I?" ,answer: "Secret.", keyword: "secret")
Riddle.create(question: "How many times can you subtract the number two from the number fifty?", answer: "22.", keyword: "22")
Riddle.create(question: "What word in the English language is always spelled incorrectly?", answer: "Incorrectly", keyword: "incorrectly")
Riddle.create(question: "Without it, I'm dead. If I'm not, then I'm behind. What am I?", answer: "A head.", keyword: "head")
Riddle.create(question: "What's full of holes but can still hold water?", answer: "A sponge.", keyword: "sponge")
Riddle.create(question: "If you were running a race and you passed the person in 2nd place, what place would you be in now?", answer: "2nd place.", keyword: "2nd")
Riddle.create(question: "I am in heaven but not in hell. I’m in the devil but not in god. I’m in the river but not in the sea. What am I?", answer: "The letter 'v'", keyword: "v")
Riddle.create(question: "We hurt without moving. And poison without touching. We bear truth and lies, But are not judged by size. What are we?", answer: "Words", keyword: "words")
Riddle.create(question: "You bury me when I’m alive, and dig me up when I’m dead. What am I?", answer: "A plant.", keyword: "plant")
Riddle.create(question: "What asks but never answers?", answer: "An owl.", keyword: "owl")
Riddle.create(question: "If you lose me, others around you may lose me too. What am I?", answer: "Your temper.", keyword: "temper")
Riddle.create(question: "I grow in trees, eat living things but have no teeth and give birth to something that looks nothing like me. What am I?", answer: "A bird.", keyword: "bird")
Riddle.create(question: "I have two hands but I cannot clap. What am I?", answer: "A clock.", keyword: "clock")
Riddle.create(question: "It stalks the countryside, with ears that cannot hear. What is it?", answer: "Corn.", keyword: "corn")
Riddle.create(question: "Anyone can take it as long as it’s on someone.", answer: "Pity.", keyword: "pity")
Riddle.create(question: "I died and came back to life. My blood is not easily able to go through my body. My favorite pet is a fish. Who am I?", answer: "A shark.", keyword: "shark")
Riddle.create(question: "I travel a lot and meet both the rich and the poor, but nobody knows where I am going next. I’m invisible but you can see what I do. Who or what am I?", answer: "The wind.", keyword: "wind")
Riddle.create(question: "What can go up a drainpipe down but not down a drainpipe up?", answer: "An umbrella.", keyword: "umbrella")
Riddle.create(question: "If you look at my face you won’t see 13 in any place. What am I?", answer: "A clock face.", keyword: "clock")
Riddle.create(question:"No thicker than your finger when it folds. As thick as what it’s holding when it holds.", answer:"A sack.", keyword: "sack")
Riddle.create(question: "It is hate and has hate in it, but it isn’t hate.", answer: "Hatred.", keyword: "hatred")
Riddle.create(question: "It can only exist between any two things, and men know it well for the hardships it brings.", answer: "Distance.", keyword: "distance")
Riddle.create(question: "One strand dangles. Two strands twist. Three or more can fashion this.", answer: "A braid.", keyword: "braid")
Riddle.create(question: "I’m so simple I only point, Yet I guide people all over the world. What am I?", answer: "A compass.", keyword: "compass")
Riddle.create(question: "Apples for leather, leather for silk, silk for tobacco, all to get milk.", answer: "Bartering.", keyword: "bartering")
Riddle.create(question: "When pronounced, it sounds nothing like the word.", answer: "A sentence.", keyword: "sentence")
Riddle.create(question: "What has hair and leaks when something bad happens?", answer: "Your eye.", keyword: "eye")
Riddle.create(question: "What has three feet but no head?", answer: "A yardstick.", keyword: "yardstick")
Riddle.create(question:"Tear one off and scratch my head what was red is black instead. What am I?", answer:"Matchstick", keyword: "matchstick")
Riddle.create(question:"What can travel around the world while staying in a corner?", answer:"Stamp", keyword: "stamp")
Riddle.create(question:"Which word in the dictionary is spelled incorrectly?", answer:"Incorrectly", keyword: "incorrectly")
Riddle.create(question:"What invention lets you look right through a wall?", answer:"Window", keyword: "window")
Riddle.create(question:"What can you catch but not throw?", answer:"Cold", keyword: "cold")
Riddle.create(question:"What is as light as a feather, but even the world's strongest man couldn't hold it for more than a minute?", answer:"Breath", keyword: "breath")
Riddle.create(question:"What has four fingers and a thumb, but is not living?", answer:"Glove", keyword: "glove")
Riddle.create(question:"What flies when it's born, lies when it's alive and runs when it's dead?", answer:"Snowflake", keyword: "snowflake")
Riddle.create(question:"I am always there, some distance away, somewhere between land and sea and sky I lay, you may move towards me, yet distant I'll stay.", answer:"Horizon", keyword: "horizon")
Riddle.create(question:"I am a mother and a father, but have never given birth. I'm rarely still, but I never wander. What am I?", answer:"Tree", keyword: "tree")
Riddle.create(question:"I can only live where there is light, but I die if the light shines on me. What am I?", answer:"A Shadow", keyword: "shadow")
Riddle.create(question:"Every night I'm told what to do. And every morning I do as I'm told. But I still can't escape your scold! What am I?", answer:"Alarm Clock", keyword: "alarm")
Riddle.create(question:"What gets broken without being held?", answer:"A promise.", keyword: "promise")
Riddle.create(question:"What is always coming but never arrives?", answer:"Tomorrow", keyword: "tomorrow")
Riddle.create(question:"What goes through towns and over hills but never moves?", answer:"A Road", keyword: "road")
Riddle.create(question:"What has Eighty-eight keys but can’t open a single door?", answer:"A piano", keyword: "piano")
Riddle.create(question:"What has a neck but no head?", answer:"A bottle", keyword: "bottle")
Riddle.create(question:"A monkey, a squirrel, and a bird are racing to the top of a coconut tree. Who will get the banana first, the monkey, the squirrel, or the bird?", answer:"None of them, because you can’t get a banana from a coconut tree!", keyword: "none")
Riddle.create(question:"Which eight-letter word still remains a word after removing each letter from it?", answer:"Starting-Staring-String-Sting-Sing-Sin-In-I.", keyword: "starting")
Riddle.create(question:"What has a head but never weeps, has a bed but never sleeps, can run but never walks, and has a bank but no money?", answer:"A river!", keyword: "river")
Riddle.create(question:"What has 4 legs in the morning, 2 legs in the afternoon, and 3 legs at night?", answer:"A person! As a baby you crawl (4 legs), as an adult you walk (2 legs), then when you are older you use a cane (3 legs)", keyword: "person")
Riddle.create(question:"The more it dries, the wetter it becomes. What is it?", answer:"A towel!", keyword: "towel")
Riddle.create(question:"What can you hear but not touch or see?", answer:"Your voice.", keyword: "voice")
Riddle.create(question:"What starts with “P” and ends with “E” and has more than 1000 letters?", answer:"A post office!", keyword: "post office")
Riddle.create(question:"What loses its head in the morning but gets it back at night?", answer:"A pillow", keyword: "pillow")
Riddle.create(question:"Can you name the two days starting with T besides Tuesday and Thursday?", answer:"Today and tomorrow.", keyword: "today")
Riddle.create(question:"What is round on both sides but high in the middle?", answer:"Ohio.", keyword: "ohio")
Riddle.create(question:"If two’s company and three’s a crowd, what are four and five?", answer:"Nine!", keyword: "nine")
Riddle.create(question:"What is the center of Gravity?", answer:"The letter V.", keyword: "V")
Riddle.create(question:"What is the last thing you take off before bed?", answer:"Your feet off the floor.", keyword: "feet")
Riddle.create(question:"I have keys but no locks. I have space but no room. You can enter but can’t go outside. What am I?", answer:"A Keyboard", keyword: "keyboard")
Riddle.create(question:"What is next in this sequence: JFMAMJJASON_ ?", answer:"The letter D. The sequence contains the first letter of each month.", keyword: "D")
Riddle.create(question:"How many seconds are there in a year?", answer:"12. (January 2nd, February 2nd, March 2nd….)", keyword: "12")
Riddle.create(question:"One night, a butcher, a baker and a candlestick maker go to a hotel. When they get their bill, however, it’s for four people. Who’s the fourth person?", answer:"One night can also mean one knight. That makes four: one knight, a butcher, a baker and a candlestick maker!", keyword: "knight")
Riddle.create(question:"What instrument can you hear but never see?", answer:"Your voice! You can sing with your voice like an instrument and hear it, but no one can see it!", keyword: "voice")
Riddle.create(question:"What kind of room has no doors or windows?", answer:"A mushroom.", keyword: "mushroom")
Riddle.create(question:"What loses its head in the morning and gets it back at night?", answer:"A pillow.", keyword: "pillow")
Riddle.create(question:"What has 3 feet but cannot walk?", answer:"A yardstick.", keyword: "yardstick")
Riddle.create(question:"What belongs to you but others use it more than you do?", answer:"Your name.", keyword: "name")
Riddle.create(question:"What kind of coat can only be put on when wet?", answer:"A coat of paint.", keyword: "paint")
Riddle.create(question:"Why is a raven like a writing desk?", answer:"Edgar Allan Poe wrote on both of them.", keyword: "Edgar Allan Poe")
Riddle.create(question:"What can be swallowed, but can swallow you?", answer:"Pride", keyword: "Pride")
Riddle.create(question:"What is so delicate that even mentioning it breaks it?", answer:"Silence", keyword: "silence")
Riddle.create(question:"What goes up, lets out a load, then goes back down?", answer:"An elevator! (Or penis)", keyword: "elevator")
Riddle.create(question:"What has ten letters and starts with gas?", answer:"An automobile", keyword: "automobile")
Riddle.create(question:"I am the beginning of the end, the end of every place. I am the beginning of eternity, the end of time and space. What am I?", answer:"The letter E.", keyword: "E")
Riddle.create(question:"I am very easy to get into,but it is hard to get out of me.What am I?", answer:"Trouble", keyword: "trouble")
Riddle.create(question:"What heavy seven letter word can you take two away from and be left with eight?", answer:"Weights", keyword: "weights")
Riddle.create(question:"What is the coolest letter in the alphabet?", answer:"'B', because it's always surrounded by AC.", keyword: "B")
Riddle.create(question:"What has teeth but can't bite?", answer:"A comb.", keyword: "comb")
Riddle.create(question:"What always murmurs but never talks, Always runs but never walks, Has a bed but never sleeps, Has a mouth but never speaks?", answer:"A river.", keyword: "river")
Riddle.create(question:"What tastes better than it smells?", answer:"A tongue.", keyword: "tongue")
Riddle.create(question:"What two things can you never eat for breakfast?", answer:"Lunch and breakfast.", keyword: "lunch")
Riddle.create(question:"What happens when you throw a blue rock into the yellow sea?", answer:"It sinks.", keyword: "sinks")
Riddle.create(question:"What gets longer when pulled,fits between breasts, slides neatly into a hole,has choked people when used improperly,and works best when jerked?", answer:"A seatbelt.", keyword: "seatbelt")
Riddle.create(question:"Imagine you are swimming in the ocean and a bunch of hungry sharks surround you. How do you get out alive?", answer:"Stop imagining.", keyword: "imagining")
Riddle.create(question:"I build bridges of silver and crowns of gold. Who am I?", answer:"A dentist", keyword: "dentist")
Riddle.create(question:"Though I live beneath a roof, I never seem to dry. If you will only hold me, I swear I will not lie.", answer:"A tongue.", keyword: "tongue")
Riddle.create(question:"What is it that nobody wants, yet nobody wants to lose?", answer:"A lawsuit.", keyword: "lawsuit")
Riddle.create(question:" I can be flipped and broken but I never move. I can be closed, and opened, and sometimes removed. I am sealed by hands. What am I?", answer:"A deal.", keyword: "deal")
Riddle.create(question:"What has a foot but no legs?", answer:"A snail", keyword: "snail")
Riddle.create(question:"Poor people have it. Rich people need it. If you eat it you die. What is it?", answer:"Nothing", keyword: "nothing")
Riddle.create(question:"What comes down but never goes up?", answer:"Rain", keyword: "rain")
Riddle.create(question:"I’m tall when I’m young and I’m short when I’m old. What am I?", answer:"A candle", keyword: "candle")
Riddle.create(question:"Mary’s father has 5 daughters – Nana, Nene, Nini, Nono. What is the fifth daughters name?", answer:"Mary", keyword: "mary")
Riddle.create(question:"How can a pants pocket be empty and still have something in it?", answer:"It can have a hole in it.", keyword: "hole")
Riddle.create(question:"What goes up when rain comes down?", answer:"An umbrella!", keyword: "umbrella")
Riddle.create(question:"What is the longest word in the dictionary?", answer:"Smiles, because there is a mile between each ‘s’", keyword: "smiles")
Riddle.create(question:"If I drink, I die. If I eat, I am fine. What am I?", answer:"A fire!", keyword: "fire")
Riddle.create(question:"Throw away the outside and cook the inside, then eat the outside and throw away the inside. What is it?", answer:"Corn on the cob, because you throw away the husk, cook and eat the kernels, and throw away the cob.", keyword: "corn")
Riddle.create(question:"What word becomes shorter when you add two letters to it?", answer:"Short", keyword: "short")
Riddle.create(question:"What travels around the world but stays in one spot?", answer:"A stamp!", keyword: "stamp")
Riddle.create(question:"What occurs once in a minute, twice in a moment and never in one thousand years?", answer:"The letter M", keyword: "M")
Riddle.create(question:"What has 4 eyes but can’t see?", answer:"Mississippi", keyword: "Mississippi")
User.create(name: "diane", phone_number: "16313275832")
